version: '3.8'

services:
  pycook-database:
    image: postgres:14.1-alpine
    build:
      context: ./docker/images/postgres/
    healthcheck:
      test: [ "CMD", "/usr/healthcheckInit.sh" ]
      interval: 2s
      timeout: 5s
      retries: 20
    restart: always
    env_file:
      - docker/env/postgres.env
    ports:
      - '5432:5432'
    command: "postgres -c max_connections=300 -c log_min_messages=LOG"
    volumes:
      - "db-data:/docker-entrypoint-initdb.d/"


  pycook-api:
    build:
      dockerfile: ./docker/images/pycook-api/Dockerfile
      context: .
    ports:
      - "5000:5000"
    command: ["flask", "run"]
    depends_on:
      - pycook-database


volumes:
  db-data:
    driver_opts:
      type: tmpfs
      device: tmpfs