version: '3.1'

services:
 # db:
 #   image: postgres:14.1-alpine
 #   restart: always
 #   environment:
 #     - POSTGRES_USER=postgres
 #     - POSTGRES_PASSWORD=postgres
 #   ports:
 #     - '5432:5432'
 #   command: "postgres -c max_connections=300 -c log_min_messages=LOG"
 #   volumes:
 #     - "db-data:/var/lib/postgresql/data"
  web:
    build: .
    ports:
      - "8000:5000"


volumes:
  db-data:
    driver_opts:
      type: tmpfs
      device: tmpfs